# Generated by Django 5.2.7 on 2025-11-27 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0005_alter_vehicle_v_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_type', models.CharField(choices=[('CAR', 'Car'), ('TRAVELLER_MINI', 'Traveller Bus (Mini)'), ('TOURIST_BUS', 'Tourist Bus'), ('LUXURY', 'Luxury Bus')], max_length=30)),
                ('v_seat', models.IntegerField(choices=[(4, '4 Seater'), (5, '5 Seater'), (7, '7 Seater'), (11, '11 Seater'), (17, '17 Seater'), (25, '25 Seater'), (31, '31 Seater'), (40, '40 Seater'), (50, '50+ Seater')])),
                ('v_provider', models.CharField(help_text='Name of the vehicle service provider', max_length=255)),
                ('v_model', models.CharField(max_length=100)),
                ('pickup_address', models.TextField()),
                ('pickup_lat', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_lng', models.CharField(blank=True, max_length=50, null=True)),
                ('booking_from', models.DateField()),
                ('booking_to', models.DateField()),
                ('purpose', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=255)),
                ('pickup_time', models.TimeField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='agency.agency')),
            ],
        ),
    ]
