# Generated by Django 5.2.7 on 2025-11-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_alter_vehicle_v_type'),
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
    ]
