# Generated by Django 5.2.7 on 2025-11-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_rename_bookings_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='v_provider',
        ),
    ]
