# Generated by Django 5.2.7 on 2025-11-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_remove_booking_v_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pickup_lat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_lng',
        ),
    ]
