# Generated by Django 5.2.7 on 2025-11-27 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_alter_vehicle_v_type'),
        ('ride', '0004_remove_booking_pickup_lat_remove_booking_pickup_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='v_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='agency.vehicle'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='v_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
