# Generated by Django 5.2.7 on 2025-11-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_booking_pickup_lat_booking_pickup_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pickup_lat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_lng',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='v_provider',
        ),
    ]
