# Generated by Django 5.2.7 on 2025-11-29 09:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_remove_booking_pickup_lat_remove_booking_pickup_lng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile', models.CharField(db_index=True, max_length=20)),
                ('booking_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='pending', max_length=64)),
                ('driver_name', models.CharField(blank=True, max_length=120)),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
