# Generated by Django 5.2.7 on 2025-11-29 08:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0005_alter_vehicle_v_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetAmount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manual_amount', models.DecimalField(decimal_places=2, default=0, help_text='Manual price set after booking or default base price', max_digits=10)),
                ('is_fixed', models.BooleanField(default=False, help_text='True → Fixed pricing applied; False → Manual pricing only')),
                ('min_km', models.PositiveIntegerField(blank=True, default=0, help_text='Minimum KM allowed for fixed amount per km')),
                ('amount_per_km', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('flat_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('flat_max_km', models.PositiveIntegerField(blank=True, default=0)),
                ('extra_after_flat_per_km', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Optional rate when distance > flat_max_km', max_digits=10)),
                ('night_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('other_charges', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='set_amount', to='agency.vehicle')),
            ],
        ),
    ]
