# Generated by Django 5.2.7 on 2025-12-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setamount',
            name='other_charges',
        ),
        migrations.RemoveField(
            model_name='setamount',
            name='tax_percent',
        ),
    ]
