# Generated by Django 5.2.7 on 2025-12-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_setamount_other_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setamount',
            name='extra_after_flat_per_km',
        ),
    ]
