# Generated by Django 5.2.7 on 2025-12-13 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_setamount_extra_after_flat_per_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setamount',
            name='flat_amount',
        ),
        migrations.RemoveField(
            model_name='setamount',
            name='flat_max_km',
        ),
    ]
