# Generated by Django 5.2.7 on 2025-11-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_type', models.CharField(choices=[('CAR', 'Car'), ('BUS', 'Bus'), ('TRAVELLER', 'Traveller Bus'), ('LUXURY', 'Luxury Bus')], max_length=20)),
                ('v_seat', models.IntegerField(choices=[(4, '4 Seater'), (5, '5 Seater'), (7, '7 Seater'), (11, '11 Seater'), (17, '17 Seater'), (25, '25 Seater'), (31, '31 Seater'), (40, '40 Seater'), (50, '50+ Seater')])),
                ('v_model', models.CharField(max_length=100)),
                ('v_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Maintenence', 'maintenence'), ('Available', 'Available'), ('Booked', 'Booked')], default='Available', max_length=20)),
                ('v_img', models.ImageField(upload_to='Vehicle_images')),
                ('pollution', models.DateField()),
                ('permint', models.DateField()),
                ('fitness', models.DateField()),
                ('authorize', models.DateField()),
                ('insurance', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='add_vehicle',
        ),
    ]
