# Generated by Django 5.2.7 on 2025-11-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_vehicle_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='v_type',
            field=models.CharField(choices=[('CAR', 'Car'), ('TRAVELLER (MINI)', 'Traveller Bus (Mini)'), ('TOURIST BUS', 'Tourist Bus'), ('LUXURY', 'Luxury Bus')], max_length=20),
        ),
    ]
