# Generated by Django 5.2.7 on 2025-12-13 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_alter_vehicle_v_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_img', models.ImageField(upload_to='Driver_images')),
                ('driver_dob', models.DateField(blank=True, null=True)),
                ('driver_age', models.IntegerField(blank=True, null=True)),
                ('driver_phone', models.CharField(max_length=10)),
                ('licence_number', models.CharField(max_length=20)),
                ('licence_type', models.CharField(choices=[('LMV', 'LMV'), ('HMV', 'HMV')], max_length=10)),
                ('valid_till', models.DateField()),
                ('licence_file', models.FileField(blank=True, null=True, upload_to='Licence_files')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='agency.agency')),
            ],
        ),
    ]
