# Generated by Django 5.2.7 on 2025-12-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='valid_till',
            new_name='validity',
        ),
    ]
