# Generated by Django 5.2.7 on 2025-12-13 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_rename_valid_till_driver_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='authorized_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_vehicles', to='agency.driver'),
        ),
    ]
